import { saveSmartMoneyWallet } from '../src/database.js';
import type { SmartMoneyWallet } from '../src/types.js';

const seededAt = Date.parse('2026-04-06T10:00:00+08:00');

const seeds: SmartMoneyWallet[] = [
  {
    address: 'CyaE1VxvBrahnPWkqm5VsdCvyS2QmNht2UFrKJHga54o',
    label: 'GMGN Smart Money #1',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +5.9M; top ranked smart wallet.',
    winRate: 0.72,
    avgROI: 2.8,
    totalTrades: 450,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-1',
  },
  {
    address: '5M8ACGKEXG1ojKDTMH3sMqhTihTgHYMSsZc6W8i7QW3Y',
    label: 'GMGN Smart Money #2',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +627.9k.',
    winRate: 0.68,
    avgROI: 2.3,
    totalTrades: 320,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-2',
  },
  {
    address: 'bwamJzztZsepfkteWRChggmXuiiCQvpLqPietdNfSXa',
    label: 'GMGN Smart Money #3',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +173.9k.',
    winRate: 0.65,
    avgROI: 2.1,
    totalTrades: 280,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-3',
  },
  {
    address: '22vL22PcYcoAVCwYN8iDW9VrFEYq93TCtr7a6avNVyjL',
    label: 'GMGN Smart Money #4',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +160.6k.',
    winRate: 0.64,
    avgROI: 2.0,
    totalTrades: 260,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-4',
  },
  {
    address: '515vh1DrPuwMATt9Zoq9kP4sJL9fyojA1dHJu4DQpNRp',
    label: 'GMGN Smart Money #5',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +134.8k.',
    winRate: 0.62,
    avgROI: 1.9,
    totalTrades: 240,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-5',
  },
  {
    address: '2wHHnAmdhFaAAsayWAeqKe3snK3KkbRQkRgLwTtz7iCi',
    label: 'GMGN Smart Money #6',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +121.7k.',
    winRate: 0.61,
    avgROI: 1.8,
    totalTrades: 220,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-6',
  },
  {
    address: '9yxmCNwZcHe63NucU9yvCt7b1ja3jwP9v4T3yFMkQ1Z9',
    label: 'GMGN Smart Money #7',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +116.9k.',
    winRate: 0.60,
    avgROI: 1.7,
    totalTrades: 210,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-7',
  },
  {
    address: 'VJSDW6S74YXR4rRR9P4xwhMvLZJQMhrUb8XMFirUsy1',
    label: 'GMGN Smart Money #8',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +114.3k.',
    winRate: 0.59,
    avgROI: 1.6,
    totalTrades: 200,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-8',
  },
  {
    address: '8oEdL8WBRpE3C63FeqZ7hwSH8fjh715ZvkgmMLhDneGm',
    label: 'GMGN Smart Money #9',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +105.2k.',
    winRate: 0.58,
    avgROI: 1.5,
    totalTrades: 190,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-9',
  },
  {
    address: '8HcYptCBAaPFWkmupiSAmysZ6Z8jB7N1c4YhVjhX7zbg',
    label: 'GMGN Smart Money #10',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +98.8k.',
    winRate: 0.57,
    avgROI: 1.5,
    totalTrades: 180,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-10',
  },
  {
    address: '2AqFJzcgSMQ9v7Vwh4yE7Vux8brcrjus1eg4K1zM2zUd',
    label: 'GMGN Smart Money #11',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +96.8k.',
    winRate: 0.56,
    avgROI: 1.4,
    totalTrades: 170,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-11',
  },
  {
    address: '7VHRg4Wi55NtnK68VRjWwhy4x1XYF846DHWnPBXwRmnv',
    label: 'GMGN Smart Money #12',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +92.2k.',
    winRate: 0.55,
    avgROI: 1.4,
    totalTrades: 160,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-12',
  },
  {
    address: 'CQKJHYqVPn8P944dpQtNud5eVLQr4p8iFuKSVNgKYNxY',
    label: 'GMGN Smart Money #13',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +89.9k.',
    winRate: 0.54,
    avgROI: 1.3,
    totalTrades: 150,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-13',
  },
  {
    address: 'JBV41vYBL2b8HuBmNcCnpRoBfrLDJrUFViQFPJ2vZrWd',
    label: 'GMGN Smart Money #14',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +78.6k.',
    winRate: 0.53,
    avgROI: 1.3,
    totalTrades: 140,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-14',
  },
  {
    address: '5ZuV8eqkvzYFVEKbLvGBdexL2tFv7E5BCd2HZpjqbdg',
    label: 'GMGN Smart Money #15',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +74.1k.',
    winRate: 0.52,
    avgROI: 1.2,
    totalTrades: 130,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-15',
  },
  {
    address: 'GpTXmkdvrTajqkzX1fBmC4BUjSboF9dHgfnqPqj8WAc4',
    label: 'GMGN Smart Money #16',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +72.3k.',
    winRate: 0.51,
    avgROI: 1.2,
    totalTrades: 120,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-16',
  },
  {
    address: '7szNtB9WXHpUdyGiBvMRaYouBBTsL2QbTtYrig8wo2vP',
    label: 'GMGN Smart Money #17',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +50.2k.',
    winRate: 0.50,
    avgROI: 1.1,
    totalTrades: 110,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-17',
  },
  {
    address: '4BdKaxN8G6ka4GYtQQWk4G4dZRUTX2vQH9GcXdBREFUk',
    label: 'GMGN Smart Money #18',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +39.6k.',
    winRate: 0.49,
    avgROI: 1.0,
    totalTrades: 100,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-18',
  },
  {
    address: '9XVWfqzavraezfvS38v8xcZepHYxcNKtnNMEKpPXEwTN',
    label: 'GMGN Smart Money #19',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +39.5k.',
    winRate: 0.48,
    avgROI: 1.0,
    totalTrades: 95,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-19',
  },
  {
    address: 'D9gQ6RhKEpnobPBUdWY5bPQt2p3zGk3iVz6ChpUi2ArA',
    label: 'GMGN Smart Money #20',
    source: 'gmgn',
    notes: 'Source: GMGN Solana smart-money leaderboard seed. 7D profit: +38.2k.',
    winRate: 0.47,
    avgROI: 1.0,
    totalTrades: 90,
    lastSeen: seededAt,
    addedAt: seededAt,
    isAutoImported: true,
    providerRef: 'gmgn-kolquest-top-20',
  },
  {
    address: '3wi8waD5A64D7PLutUYJdhMcrYvDBTqeh3CRFgv1hFtY',
    label: 'Bitget Top Wallet 2025-04-28',
    source: 'x',
    notes: 'Source: x.com/SolSmartTrader post dated 2025-04-28. Public top-wallet feed. Verify current behavior before following.',
    winRate: 0,
    avgROI: 0,
    totalTrades: 0,
    lastSeen: seededAt,
    addedAt: seededAt,
  },
  {
    address: '45yBcpnzFTqLYQJtjxsa1DdZkgrTYponCg6yLQ6LQPu6',
    label: 'Bitget Top Wallet 2025-05-02',
    source: 'x',
    notes: 'Source: x.com/SolSmartTrader post dated 2025-05-02. Public top-wallet feed. Verify current behavior before following.',
    winRate: 0,
    avgROI: 0,
    totalTrades: 0,
    lastSeen: seededAt,
    addedAt: seededAt,
  },
  {
    address: 'HXkaN7TAQYXsybY1UHLrn18cVa9jgM3mbReasbAoSjTv',
    label: 'Bitget Top Wallet 2025-03-08',
    source: 'x',
    notes: 'Source: x.com/SolSmartTrader post dated 2025-03-08. Public top-wallet feed. Verify current behavior before following.',
    winRate: 0,
    avgROI: 0,
    totalTrades: 0,
    lastSeen: seededAt,
    addedAt: seededAt,
  },
  {
    address: '6nWo1vXgY5pFj3HpexSjz3se1bnS2CVDKjPaaAA22UFh',
    label: 'Bitget Daily Smart Trader 2025-03-24 #1',
    source: 'x',
    notes: 'Source: indexed x.com/SolSmartTrader post dated 2025-03-24. Daily Smart Traders via BitgetWallet. Reported profit: +8497%.',
    winRate: 0,
    avgROI: 84.97,
    totalTrades: 0,
    lastSeen: seededAt,
    addedAt: seededAt,
  },
  {
    address: 'C52fTxWSypGHkQfE8nQuZB72E2Dqe66EybwSQkb5CAiu',
    label: 'Bitget Daily Smart Trader 2025-03-24 #2',
    source: 'x',
    notes: 'Source: indexed x.com/SolSmartTrader post dated 2025-03-24. Daily Smart Traders via BitgetWallet. Reported profit: +6155%.',
    winRate: 0,
    avgROI: 61.55,
    totalTrades: 0,
    lastSeen: seededAt,
    addedAt: seededAt,
  },
  {
    address: '2aXiwS7BnF1CK6XJ2S9ANZRY859vzMdyYek4E8DKyN3U',
    label: 'Bitget Daily Smart Trader 2025-03-24 #3',
    source: 'x',
    notes: 'Source: indexed x.com/SolSmartTrader post dated 2025-03-24. Daily Smart Traders via BitgetWallet. Reported profit: +5259%.',
    winRate: 0,
    avgROI: 52.59,
    totalTrades: 0,
    lastSeen: seededAt,
    addedAt: seededAt,
  },
  {
    address: 'JD38n7ynKYcgPpF7k1BhXEeREu1KqptU93fVGy3S624k',
    label: 'Birdeye Popular JD38',
    source: 'birdeye',
    notes: 'Source: Birdeye Wallet Tracker public profile marked Popular. URL: https://birdeye.so/solana/profile/JD38n7ynKYcgPpF7k1BhXEeREu1KqptU93fVGy3S624k',
    winRate: 0,
    avgROI: 0,
    totalTrades: 0,
    lastSeen: seededAt,
    addedAt: seededAt,
  },
  {
    address: 'Bqa5SE6WmQK4ybrMnHEvQX3gxLT91s23M76monGJGaDD',
    label: 'Birdeye Popular Bqa5',
    source: 'birdeye',
    notes: 'Source: Birdeye Wallet Tracker public profile marked Popular. URL: https://birdeye.so/solana/profile/Bqa5SE6WmQK4ybrMnHEvQX3gxLT91s23M76monGJGaDD',
    winRate: 0,
    avgROI: 0,
    totalTrades: 0,
    lastSeen: seededAt,
    addedAt: seededAt,
  },
  {
    address: 'BAG1ad6HgmFBEiSDAyf9NgSafAmbK8y9YnkKnTvt4kLT',
    label: 'Birdeye Wallet BAG1',
    source: 'birdeye',
    notes: 'Source: Birdeye Wallet Tracker public profile. URL: https://birdeye.so/solana/profile/BAG1ad6HgmFBEiSDAyf9NgSafAmbK8y9YnkKnTvt4kLT',
    winRate: 0,
    avgROI: 0,
    totalTrades: 0,
    lastSeen: seededAt,
    addedAt: seededAt,
  },
];

for (const wallet of seeds) {
  saveSmartMoneyWallet(wallet);
}

console.log(`[seed-smart-wallets] upserted ${seeds.length} wallets`);
